### ISSUE TITLE
[Product page] Code cleanup and tech debt

### ISSUE THREAD

**Issue by kmeleta** [Shopify/dawn#1936]
There are several ways we can potentially try to cleanup and improve the main product section. Having a cleaner more stable base to work from will help speed up future work and improve confidence that we're not introducing regressions along the way.

One thing that may go a long way in making the file more readable and more easily extensible is simply abstracting some elements into snippets, particularly if they are already being duplicated or used in other sections. Additionally, the css styles and classes used in the section are also a little inconsistent and sort of unorganized, making working within this scope difficult.

<strong>Priority tasks</strong>

- [x] Snippetize media gallery [#1934](https://github.com/Shopify/dawn/pull/1934)
- [x] Snippetize media modal [#1934](https://github.com/Shopify/dawn/pull/1934)
- [ ] Snippetize additional product info blocks [#2043](https://github.com/Shopify/dawn/issues/2043) @sofiamatulis
- [ ] Cleanup/refactor main product stylesheet/classes [#2056](https://github.com/Shopify/dawn/issues/2056) @andrewetchen
- [x] Simplify global media setting styles in product-thumbnail
- [x] Improve aspect ratio styling in product-thumbnail [#2022](https://github.com/Shopify/dawn/pull/2022)
- [x] Add CSS class to reliably select :only-child with hidden variants ([example implementation](https://github.com/Shopify/dawn/commit/62497547642baa025003f1d53146034574718a42))

Other tasks
- Media/deferred media style improvements [#1931](https://github.com/Shopify/dawn/issues/1931)
- Refactor product page layout grid and associated overrides
- Use media gallery snippet for featured product? (needs investigation)
