### ISSUE TITLE
[Icons] Uniformize the growing animation on the theme

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#2427]
## Describe the enhancement you'd like

Uniformize the growing animation on the theme.

```[tasklist]
### Tasks

- [ ] Grow the cart delete icon. _(Could shrink instead?)_
- [ ] Shrink the search's clear icon _(Could feels more natural when you delete or clear something?)_
- [ ] Grow the quantity input's symbols **+ and -** 
- [ ] Grow the footer's email sign up input arrow icon
- [ ] Grow the filters' clear pill clear icon. _(Could shrink instead?)_
- [ ] Grow the collapsible row's icons to emphasize the hover state?
- [ ] Pagination arrows, we barely see the grow, could we swap the arrow for the line arrow one?
- [ ] Grow share icon
- [ ] Bring consistency for the modal's close icon
- [ ] Grow the navigation drawer's arrows for nested links
- [ ] Drawer navigation Login icon grows but the link is not growing on the label like other places, e.g. Share block, to investigate
- [ ] Cart drawer; the close icon is not animated
- [ ] Parent menu nav link don’t grow yet, just the hover
```
