### ISSUE TITLE
[Navigation UX] Allow Announcement bar to be added multiple times (stacked)

### ISSUE THREAD

**Issue by kimberlyoleiro** [Shopify/dawn#2583]
The announcement bar is currently a static section - it cannot be added or removed from its current position in the header. 

User story: As a merchant I should be able to add multiple announcement bars in my header 

**Task**

- [ ] Allow the announcement bar to be added as a section within the header group
- [ ] Limit the announcement bar to the header group only 
- [ ] Confirm upgrade path for merchants.
