### ISSUE TITLE
Update blog post default state

### ISSUE THREAD

**Issue by Oliviammarcello** [Shopify/dawn#2667]
**User Story**: As a merchant installing a new theme to use for my online store, I should be able to see an accurate representation of what my theme will look like with or without placeholder content. What I see by default, should reflect what I'll see when I upload a real image

**Ultimate Goal**: Achieve a 1:1 experience between placeholders images and real images

**More context**: With the introduction of new placeholder content, and fresh eyes on the topic, we noticed some inconsistencies between the empty and populated states with images. 

[Video here](https://videobin.shopify.io/v/10gA96)
[Notes here](https://docs.google.com/document/d/1ZVYZsJmjRJAmKOTpWYbW9-dzrZ4nVmfSpFNSvj6Iakk/edit#)

## Identified Problem:
1. The empty state of the blog does not accurately reflect the default styles & preset settings of the section

![Image](https://github.com/Shopify/dawn/assets/107572834/7ddaf748-4c89-47b6-8423-6eb0681352a9)
![Image](https://github.com/Shopify/dawn/assets/107572834/1d5bdea8-e25a-492b-8688-d04dfba3a6bb)

## Expected behaviour
The default styles of blog cards placeholder images should appear with the same styles as a if they were populated with real blog images.

## Task
- [ ] Match the placeholder image styles to the same default styles that would appear if image was populated
- [ ] Display a placeholder state that matches the same default presets available in the section
- [x] Disconnect "news" preset. The blog should be empty by default
