### ISSUE TITLE
Quick Order List refactor opportunities

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#2928]
## Refactor opportunities for the Quick Order List section

- [ ] Pull out some of the duplicate functions in `cart.js` and `quick-order-list.js` https://github.com/Shopify/dawn/issues/2955
- [ ] Update `<quantity>` to use the `quantity-input` snippet in all places of the theme https://github.com/Shopify/dawn/issues/2953
- [x] Pull out some of the duplicate classes in `component-items-cart.css` and `quick-order-list.css` (table related) https://github.com/Shopify/dawn/issues/2956
- [x] Add loading-overlay snippet to other parts of the theme where it’s used https://github.com/Shopify/dawn/issues/2954
- [ ] Remove the hidden [vol pricing list](https://github.com/Shopify/dawn/blob/main/snippets/quick-order-list-row.liquid#L461) and use the vol pricing list in the popover instead to calculate the price per item https://github.com/Shopify/dawn/issues/2957

**Need to be investigated a bit more:**
- [ ] Refactor Filter (long file) and remove duplicate sections
- [ ] Improve performance for high amounts of variants
