### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by TEMU2000** [Shopify/dawn#3172]
## Additional context/screenshots

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/dawn/pull/3145
```

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/dawn/issues/3171
- [ ] https://github.com/Shopify/dawn/pull/3142
- [ ] https://github.com/Shopify/dawn/pull/3145
- [ ] https://github.com/Shopify/dawn/pull/3169
- [ ] https://github.com/Shopify/dawn/pull/3166
- [ ] https://github.com/Shopify/dawn/pull/3167
- [ ] https://github.com/Shopify/dawn/issues/3170
- [ ] https://github.com/Shopify/dawn/pull/3135
- [ ] https://github.com/Shopify/dawn/pull/3165
- [ ] https://github.com/Shopify/dawn/pull/3168
- [ ] https://github.com/Shopify/dawn/issues/3046
```
